import {
  Student,
  Mentor,
  Hod,
  Department,
  Shift,
  GpsVerification,
  DepartmentAlert,
  AdminActivityLog,
  HospitalGeofence,
  UserProfile,
  StudentAttendanceRecord,
  StudentNotification,
  MentorNotification,
  ShiftSession,
  ScheduledRandomCheck,
} from '../types';

export const INITIAL_SHIFT_SESSIONS: ShiftSession[] = [
  {
    shift_session_id: 'session_23ucct001_initial',
    register_number: '23UCCT001',
    student_name: 'V. ABINAYA',
    shift_id: 'shift_night_01',
    shift_name: 'Night',
    department: 'Critical Care Technology (CCT)',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    scheduled_start: '10:00 PM',
    scheduled_end: '06:00 AM',
    start_datetime: '2026-09-05T22:00:00.000Z',
    end_datetime: '2026-09-06T06:00:00.000Z',
    actual_start: '10:02 PM',
    initial_latitude: 11.9163,
    initial_longitude: 79.6277,
    initial_accuracy: 6.0,
    initial_distance: 42,
    initial_status: 'VERIFIED',
    status: 'ACTIVE',
    created_at: '2026-09-05T22:02:00.000Z',
  },
];

export const INITIAL_SCHEDULED_CHECKS: ScheduledRandomCheck[] = [
  {
    id: 'scheduled_check_session_23ucct001_initial_1',
    shift_session_id: 'session_23ucct001_initial',
    register_number: '23UCCT001',
    student_id: '23UCCT001',
    student_name: 'V. ABINAYA',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    department: 'Critical Care Technology (CCT)',
    check_number: 1,
    scheduled_time: '11:18 PM',
    scheduled_datetime: '2026-09-05T23:18:00.000Z',
    status: 'VERIFIED',
    executed_at: '2026-09-05T23:18:00.000Z',
    latitude: 11.9163,
    longitude: 79.6277,
    accuracy: 5.5,
    distance_from_hospital: 38,
    geofence_radius: 250,
    gps_state: 'INSIDE_HOSPITAL',
    permission_state: 'GRANTED',
    result: 'VERIFIED',
    created_at: '2026-09-05T22:02:00.000Z',
  },
  {
    id: 'scheduled_check_session_23ucct001_initial_2',
    shift_session_id: 'session_23ucct001_initial',
    register_number: '23UCCT001',
    student_id: '23UCCT001',
    student_name: 'V. ABINAYA',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    department: 'Critical Care Technology (CCT)',
    check_number: 2,
    scheduled_time: '01:42 AM',
    scheduled_datetime: '2026-09-06T01:42:00.000Z',
    status: 'VERIFIED',
    executed_at: '2026-09-06T01:42:00.000Z',
    latitude: 11.9163,
    longitude: 79.6277,
    accuracy: 4.8,
    distance_from_hospital: 32,
    geofence_radius: 250,
    gps_state: 'INSIDE_HOSPITAL',
    permission_state: 'GRANTED',
    result: 'VERIFIED',
    created_at: '2026-09-05T22:02:00.000Z',
  },
  {
    id: 'scheduled_check_session_23ucct001_initial_3',
    shift_session_id: 'session_23ucct001_initial',
    register_number: '23UCCT001',
    student_id: '23UCCT001',
    student_name: 'V. ABINAYA',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    department: 'Critical Care Technology (CCT)',
    check_number: 3,
    scheduled_time: '03:42 AM',
    scheduled_datetime: '2026-09-06T03:42:00.000Z',
    status: 'NEEDS ATTENTION',
    executed_at: '2026-09-06T03:42:00.000Z',
    latitude: 11.9238,
    longitude: 79.6342,
    accuracy: 18.0,
    distance_from_hospital: 850,
    geofence_radius: 250,
    gps_state: 'OUTSIDE_HOSPITAL',
    permission_state: 'GRANTED',
    result: 'NEEDS ATTENTION',
    created_at: '2026-09-05T22:02:00.000Z',
  },
  {
    id: 'scheduled_check_session_23ucct001_initial_4',
    shift_session_id: 'session_23ucct001_initial',
    register_number: '23UCCT001',
    student_id: '23UCCT001',
    student_name: 'V. ABINAYA',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    department: 'Critical Care Technology (CCT)',
    check_number: 4,
    scheduled_time: '04:50 AM',
    scheduled_datetime: '2026-09-06T04:50:00.000Z',
    status: 'SCHEDULED',
    created_at: '2026-09-05T22:02:00.000Z',
  },
  {
    id: 'scheduled_check_session_23ucct001_initial_5',
    shift_session_id: 'session_23ucct001_initial',
    register_number: '23UCCT001',
    student_id: '23UCCT001',
    student_name: 'V. ABINAYA',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    department: 'Critical Care Technology (CCT)',
    check_number: 5,
    scheduled_time: '05:40 AM',
    scheduled_datetime: '2026-09-06T05:40:00.000Z',
    status: 'SCHEDULED',
    created_at: '2026-09-05T22:02:00.000Z',
  },
];

export const HOSPITAL_CONFIG: HospitalGeofence = {
  name: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
  latitude: 11.9163,
  longitude: 79.6277,
  radius_meters: 250,
  tolerance_meters: 20,
  department_zone: 'School of Allied Health Sciences Clinical Complex',
  address: 'Kalitheerthalkuppam, Madagadipet, Puducherry - 605 107',
  last_updated_at: '2026-09-05 09:00',
  updated_by: 'SMVMCH Administration',
};

export interface GeofencePreset {
  id: string;
  name: string;
  department_zone: string;
  latitude: number;
  longitude: number;
  radius_meters: number;
  tolerance_meters: number;
  description: string;
}

export const HOSPITAL_PRESETS: GeofencePreset[] = [
  {
    id: 'smvmch_main',
    name: 'SMVMCH - Main Medical College & Hospital',
    department_zone: 'Emergency, ICU, Central Lab & Inpatient Blocks',
    latitude: 11.9163,
    longitude: 79.6277,
    radius_meters: 250,
    tolerance_meters: 20,
    description: 'Primary teaching hospital complex and allied health science clinical blocks',
  },
  {
    id: 'smvmch_ot_icu',
    name: 'SMVMCH - OT Complex & Critical Care Wing',
    department_zone: 'Main OT, Cardiac OT, Trauma ICU & Post-Op Wards',
    latitude: 11.9170,
    longitude: 79.6282,
    radius_meters: 150,
    tolerance_meters: 15,
    description: 'Specialty surgical operating theaters and intensive care stations',
  },
  {
    id: 'smvmch_labs',
    name: 'Central Diagnostic Labs & Blood Bank Pavilion',
    department_zone: 'Biochemistry, Pathology, Microbiology & Blood Bank',
    latitude: 11.9158,
    longitude: 79.6270,
    radius_meters: 120,
    tolerance_meters: 15,
    description: 'Automated diagnostic pathology labs and component blood banking unit',
  },
  {
    id: 'smvmch_imaging',
    name: 'Diagnostic Radiology & Dialysis Center',
    department_zone: 'MRI, CT Scan, Ultrasound & Dialysis Unit 1',
    latitude: 11.9168,
    longitude: 79.6265,
    radius_meters: 140,
    tolerance_meters: 15,
    description: 'Advanced clinical imaging scanners and multi-station dialysis unit',
  },
  {
    id: 'smvmch_campus',
    name: 'Sri Manakula Vinayagar Educational Complex',
    department_zone: 'Full University Campus, AHS Blocks & Hostels',
    latitude: 11.9163,
    longitude: 79.6277,
    radius_meters: 450,
    tolerance_meters: 30,
    description: 'Comprehensive perimeter covering academic halls, research centers, and hospital wards',
  },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shift_gen_ahs',
    name: 'General Clinical Duty',
    start_time: '08:30',
    end_time: '16:00',
    label: 'General Day (08:30 AM - 04:00 PM)',
    is_continuous_night: false,
  },
  {
    id: 'shift_ot_ahs',
    name: 'OT & Procedure Duty',
    start_time: '08:30',
    end_time: '16:30',
    label: 'OT Duty (08:30 AM - 04:30 PM)',
    is_continuous_night: false,
  },
  {
    id: 'shift_dialysis_morn',
    name: 'Dialysis Morning Shift',
    start_time: '08:30',
    end_time: '14:00',
    label: 'Dialysis Morning (08:30 AM - 02:00 PM)',
    is_continuous_night: false,
  },
  {
    id: 'shift_dialysis_aft',
    name: 'Dialysis Afternoon Shift',
    start_time: '13:30',
    end_time: '19:30',
    label: 'Dialysis Afternoon (01:30 PM - 07:30 PM)',
    is_continuous_night: false,
  },
  {
    id: 'shift_morning_ahs',
    name: 'Emergency Morning Shift',
    start_time: '08:00',
    end_time: '14:00',
    label: 'Morning (08:00 AM - 02:00 PM)',
    is_continuous_night: false,
  },
  {
    id: 'shift_evening_ahs',
    name: 'Evening Shift',
    start_time: '14:00',
    end_time: '20:00',
    label: 'Evening (02:00 PM - 08:00 PM)',
    is_continuous_night: false,
  },
  {
    id: 'shift_night_ahs',
    name: 'Night Emergency Duty',
    start_time: '20:00',
    end_time: '08:00',
    label: 'Night Shift (08:00 PM - 08:00 AM)',
    is_continuous_night: true,
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept_cct',
    name: 'Critical Care Technology',
    code: 'CCT',
    hod_name: 'Dr. K. Senthil Nathan',
    total_students: 12,
    active_interns: 12,
    on_shift: 8,
    verified_today: 12,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_clt',
    name: 'Cardiac Lab Technology',
    code: 'CLT',
    hod_name: 'Dr. R. Vijayakumar',
    total_students: 16,
    active_interns: 16,
    on_shift: 12,
    verified_today: 15,
    needs_attention: 1,
    gps_unavailable: 0,
  },
  {
    id: 'dept_cpt',
    name: 'Cardiac Perfusion Technology',
    code: 'CPT',
    hod_name: 'Dr. A. Venkatesh',
    total_students: 3,
    active_interns: 3,
    on_shift: 2,
    verified_today: 3,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_emt',
    name: 'Emergency Medicine Technology',
    code: 'EMT',
    hod_name: 'Dr. L. Chen',
    total_students: 8,
    active_interns: 8,
    on_shift: 5,
    verified_today: 7,
    needs_attention: 1,
    gps_unavailable: 0,
  },
  {
    id: 'dept_mlt',
    name: 'Medical Lab Technology',
    code: 'MLT',
    hod_name: 'Dr. N. Balamurugan',
    total_students: 14,
    active_interns: 14,
    on_shift: 10,
    verified_today: 14,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_otat',
    name: 'Operation Theatre & Anaesthesia Technology',
    code: 'OTAT',
    hod_name: 'Dr. S. Meenakshi',
    total_students: 10,
    active_interns: 10,
    on_shift: 7,
    verified_today: 10,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_rit',
    name: 'Radiography and Imaging Technology',
    code: 'RIT',
    hod_name: 'Dr. K. Srinivas',
    total_students: 9,
    active_interns: 9,
    on_shift: 6,
    verified_today: 9,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_nct',
    name: 'Neuro Care Technology',
    code: 'NCT',
    hod_name: 'Dr. V. Deepa',
    total_students: 4,
    active_interns: 4,
    on_shift: 3,
    verified_today: 4,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_hbbt',
    name: 'Hematology & Blood Banking Technology',
    code: 'HBBT',
    hod_name: 'Dr. R. Malathi',
    total_students: 1,
    active_interns: 1,
    on_shift: 1,
    verified_today: 1,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_rdt',
    name: 'Renal Dialysis Technology',
    code: 'RDT',
    hod_name: 'Dr. M. Balaji',
    total_students: 5,
    active_interns: 5,
    on_shift: 4,
    verified_today: 5,
    needs_attention: 0,
    gps_unavailable: 0,
  },
  {
    id: 'dept_rmce',
    name: 'Reproductive Medicine & Clinical Embryology',
    code: 'RMCE',
    hod_name: 'Dr. Kavitha S',
    total_students: 3,
    active_interns: 3,
    on_shift: 2,
    verified_today: 3,
    needs_attention: 0,
    gps_unavailable: 0,
  },
];

export const INITIAL_HODS: Hod[] = [
  {
    id: 'hod_cct',
    name: 'Dr. K. Senthil Nathan',
    department: 'Critical Care Technology',
    email: 'hod.cct@smvmch.edu.in',
    phone: '+91 94432 11001',
    is_active: true,
  },
  {
    id: 'hod_clt',
    name: 'Dr. R. Vijayakumar',
    department: 'Cardiac Lab Technology',
    email: 'hod.clt@smvmch.edu.in',
    phone: '+91 94432 11002',
    is_active: true,
  },
  {
    id: 'hod_cpt',
    name: 'Dr. A. Venkatesh',
    department: 'Cardiac Perfusion Technology',
    email: 'hod.cpt@smvmch.edu.in',
    phone: '+91 94432 11003',
    is_active: true,
  },
  {
    id: 'hod_emt',
    name: 'Dr. L. Chen',
    department: 'Emergency Medicine Technology',
    email: 'hod.emt@smvmch.edu.in',
    phone: '+91 94432 11004',
    is_active: true,
  },
  {
    id: 'hod_mlt',
    name: 'Dr. N. Balamurugan',
    department: 'Medical Lab Technology',
    email: 'hod.mlt@smvmch.edu.in',
    phone: '+91 94432 11005',
    is_active: true,
  },
  {
    id: 'hod_otat',
    name: 'Dr. S. Meenakshi',
    department: 'Operation Theatre & Anaesthesia Technology',
    email: 'hod.otat@smvmch.edu.in',
    phone: '+91 94432 11006',
    is_active: true,
  },
  {
    id: 'hod_rit',
    name: 'Dr. K. Srinivas',
    department: 'Radiography and Imaging Technology',
    email: 'hod.rit@smvmch.edu.in',
    phone: '+91 94432 11007',
    is_active: true,
  },
  {
    id: 'hod_nct',
    name: 'Dr. V. Deepa',
    department: 'Neuro Care Technology',
    email: 'hod.nct@smvmch.edu.in',
    phone: '+91 94432 11008',
    is_active: true,
  },
  {
    id: 'hod_hbbt',
    name: 'Dr. R. Malathi',
    department: 'Hematology & Blood Banking Technology',
    email: 'hod.hbbt@smvmch.edu.in',
    phone: '+91 94432 11009',
    is_active: true,
  },
  {
    id: 'hod_rdt',
    name: 'Dr. M. Balaji',
    department: 'Renal Dialysis Technology',
    email: 'hod.rdt@smvmch.edu.in',
    phone: '+91 94432 11010',
    is_active: true,
  },
  {
    id: 'hod_rmce',
    name: 'Dr. Kavitha S',
    department: 'Reproductive Medicine & Clinical Embryology',
    email: 'hod.rmce@smvmch.edu.in',
    phone: '+91 94432 11011',
    is_active: true,
  },
];

export const INITIAL_MENTORS: Mentor[] = [
  {
    id: 'mentor_cct_01',
    name: 'Dr. S. Priya',
    title: 'Senior Critical Care Supervisor',
    department: 'Critical Care Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 12,
  },
  {
    id: 'mentor_clt_01',
    name: 'Dr. M. Suresh',
    title: 'Chief Cath Lab & Echo Specialist',
    department: 'Cardiac Lab Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 16,
  },
  {
    id: 'mentor_cpt_01',
    name: 'Dr. G. Ramesh',
    title: 'Chief Perfusionist & Clinical Mentor',
    department: 'Cardiac Perfusion Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 3,
  },
  {
    id: 'mentor_emt_01',
    name: 'Dr. Dinesh Kumar',
    title: 'Emergency Medicine Clinical Supervisor',
    department: 'Emergency Medicine Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 8,
  },
  {
    id: 'mentor_mlt_01',
    name: 'Dr. P. Sharmila',
    title: 'Chief Pathologist & Lab Supervisor',
    department: 'Medical Lab Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 14,
  },
  {
    id: 'mentor_otat_01',
    name: 'Dr. K. Rajesh',
    title: 'Senior Anaesthesia Specialist & OT Supervisor',
    department: 'Operation Theatre & Anaesthesia Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 10,
  },
  {
    id: 'mentor_rit_01',
    name: 'Dr. V. Anand',
    title: 'Senior Radiologist & Imaging Supervisor',
    department: 'Radiography and Imaging Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 9,
  },
  {
    id: 'mentor_nct_01',
    name: 'Dr. T. Karthik',
    title: 'Neurophysiology & Neuro Care Supervisor',
    department: 'Neuro Care Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 4,
  },
  {
    id: 'mentor_hbbt_01',
    name: 'Dr. S. Revathi',
    title: 'Blood Bank Medical Officer & Supervisor',
    department: 'Hematology & Blood Banking Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 1,
  },
  {
    id: 'mentor_rdt_01',
    name: 'Dr. J. Sugumar',
    title: 'Chief Nephrology & Dialysis Supervisor',
    department: 'Renal Dialysis Technology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 5,
  },
  {
    id: 'mentor_rmce_01',
    name: 'Dr. R. Gayathri',
    title: 'Senior Clinical Embryologist & Supervisor',
    department: 'Reproductive Medicine & Clinical Embryology',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    assigned_students_count: 3,
  },
];

// Helper to generate avatar
const getAvatar = (idx: number) => {
  const avatars = [
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  ];
  return avatars[idx % avatars.length];
};

export const INITIAL_STUDENTS: Student[] = [
  // ==================== 1. B.Sc Critical Care Technology (12) ====================
  {
    register_number: '23UCCT001',
    enrollment_number: '230146',
    name: 'V. ABINAYA',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    internship_department: 'Critical Care Technology',
    internship_start_date: '01 Aug 2026',
    internship_end_date: '31 Jan 2027',
    internship_status: 'Active Clinical Internship',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    shift_started_at: '2026-09-05T08:30:00Z',
    current_status: 'VERIFIED',
    last_verified_at: '09:15 AM',
    last_verification_distance: 35,
    last_verification_accuracy: 10,
    avatar: getAvatar(0),
    schedules: [
      {
        id: 'sch_23ucct001_1',
        title: 'ICU & General Medicine Ward Duty',
        shift_id: 'shift_gen_ahs',
        start_time: '08:30',
        end_time: '16:00',
        time_label: '08:30 AM – 04:00 PM',
        category: 'PRIMARY_SHIFT',
        is_active: true,
      },
    ],
  },
  {
    register_number: '23UCCT002',
    enrollment_number: '230155',
    name: 'M. ANBARASAN',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    internship_department: 'Critical Care Technology',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:45 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: '23UCCT003',
    enrollment_number: '230048',
    name: 'A. ARAVIND',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:50 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: '23UCCT004',
    enrollment_number: '230151',
    name: 'DOKKA MOHANKARTHIKEYA',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:00 AM',
    avatar: getAvatar(3),
  },
  {
    register_number: '23UCCT005',
    enrollment_number: '230045',
    name: 'P. HEMALATHA',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:10 AM',
    avatar: getAvatar(4),
  },
  {
    register_number: '23UCCT007',
    enrollment_number: '230085',
    name: 'P. JAYALAKSHMI',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:40 AM',
    avatar: getAvatar(5),
  },
  {
    register_number: '23UCCT008',
    enrollment_number: '230149',
    name: 'V. KAVIYA',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:05 AM',
    avatar: getAvatar(6),
  },
  {
    register_number: '23UCCT009',
    enrollment_number: '230142',
    name: 'R. LAKSHMITHA',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:12 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: '23UCCT010',
    enrollment_number: '230157',
    name: 'R. MANJU',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_aft',
    shift_name: 'Afternoon Shift',
    shift_time: '01:30 PM – 07:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(0),
  },
  {
    register_number: '23UCCT011',
    enrollment_number: '230145',
    name: 'B. NANDHINI',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_aft',
    shift_name: 'Afternoon Shift',
    shift_time: '01:30 PM – 07:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(1),
  },
  {
    register_number: '23UCCT012',
    enrollment_number: '230134',
    name: 'E. SAFEEQA',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_aft',
    shift_name: 'Afternoon Shift',
    shift_time: '01:30 PM – 07:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(2),
  },
  {
    register_number: '23UCCT013',
    enrollment_number: '230064',
    name: 'A. SHANMUGAPRIYA',
    department: 'Critical Care Technology',
    posting_area: 'ICU, GENERAL MEDICINE WARD',
    mentor_id: 'mentor_cct_01',
    mentor_name: 'Dr. S. Priya',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_aft',
    shift_name: 'Afternoon Shift',
    shift_time: '01:30 PM – 07:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(3),
  },

  // ==================== 2. B.Sc Cardiac Lab Technology (16) ====================
  {
    register_number: 'U24CLT001',
    enrollment_number: '240041',
    name: 'S. AMEER KHAN',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:35 AM',
    avatar: getAvatar(4),
  },
  {
    register_number: 'U24CLT002',
    enrollment_number: '240062',
    name: 'S. ARAVIND KUMAR',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:42 AM',
    avatar: getAvatar(5),
  },
  {
    register_number: 'U24CLT003',
    enrollment_number: '240069',
    name: 'MR. ARUNA',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:50 AM',
    avatar: getAvatar(6),
  },
  {
    register_number: 'U24CLT004',
    enrollment_number: '240116',
    name: 'P. DIVADHRU',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:00 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: 'U23CLT005',
    enrollment_number: '230042',
    name: 'ELAKKIYA',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:38 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: 'U23CLT006',
    enrollment_number: '230055',
    name: 'V. KAMALESH',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:45 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: 'U23CLT007',
    enrollment_number: '230099',
    name: 'M. KEERTHANA',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:52 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: 'U23CLT008',
    enrollment_number: '230097',
    name: 'P. KIRUTHIGA',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:05 AM',
    avatar: getAvatar(3),
  },
  {
    register_number: 'U23CLT009',
    enrollment_number: '230112',
    name: 'I. LOURDHEMARY',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'NEEDS ATTENTION',
    last_verified_at: '09:20 AM',
    last_verification_distance: 380,
    avatar: getAvatar(4),
  },
  {
    register_number: 'U23CLT011',
    enrollment_number: '230059',
    name: 'M. PARASURAMAN',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:44 AM',
    avatar: getAvatar(5),
  },
  {
    register_number: 'U23CLT012',
    enrollment_number: '230050',
    name: 'G. RAMYTHA',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:48 AM',
    avatar: getAvatar(6),
  },
  {
    register_number: 'U23CLT013',
    enrollment_number: '230051',
    name: 'S. SHANMUGI',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:55 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: 'U23CLT014',
    enrollment_number: '230058',
    name: 'T. SRIVARSHAN',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:50 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: 'U24CLT015',
    enrollment_number: '240101',
    name: 'P. SUBASHINI',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:02 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: 'U24CLT016',
    enrollment_number: '240141',
    name: 'U. VEDHAVALLI',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:39 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: 'U24CLT017',
    enrollment_number: '240096',
    name: 'L. VISHNUPRIYA',
    department: 'Cardiac Lab Technology',
    posting_area: 'ECHO ROOM, CATH LAB, ICCU, CASUALTY',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:46 AM',
    avatar: getAvatar(3),
  },

  // ==================== 3. B.Sc Cardiac Perfusion Technology (3) ====================
  {
    register_number: '23UCPT005',
    enrollment_number: '230156',
    name: 'HARIHARAN M',
    department: 'Cardiac Perfusion Technology',
    posting_area: 'CTVS OT, ICU, WARD',
    mentor_id: 'mentor_cpt_01',
    mentor_name: 'Dr. G. Ramesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:10 AM',
    avatar: getAvatar(4),
  },
  {
    register_number: '23UCPT009',
    enrollment_number: '230105',
    name: 'SABARI VARUN KUMAR H A',
    department: 'Cardiac Perfusion Technology',
    posting_area: 'CTVS OT, ICU, WARD',
    mentor_id: 'mentor_cpt_01',
    mentor_name: 'Dr. G. Ramesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:15 AM',
    avatar: getAvatar(5),
  },
  {
    register_number: '23UCPT006',
    enrollment_number: '230102',
    name: 'MOHANRAJ V',
    department: 'Cardiac Perfusion Technology',
    posting_area: 'CTVS OT, ICU, WARD',
    mentor_id: 'mentor_cpt_01',
    mentor_name: 'Dr. G. Ramesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(6),
  },

  // ==================== 4. B.Sc Emergency Medicine Technology (8) ====================
  {
    register_number: '23UEMT001',
    enrollment_number: '230095',
    name: 'LATHITHA',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:05 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: '23UEMT002',
    enrollment_number: '230087',
    name: 'ASHIFA KATHIJA U',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:12 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: '23UEMT003',
    enrollment_number: '230126',
    name: 'JAYA LAKSHMI',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:20 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: '23UEMT004',
    enrollment_number: '230142',
    name: 'KANISHEAR K',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(2),
  },
  {
    register_number: '23UEMT005',
    enrollment_number: '230148',
    name: 'KAVIDASAN M',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(3),
  },
  {
    register_number: '23UEMT006',
    enrollment_number: '230046',
    name: 'MANIKANDAN',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_night_ahs',
    shift_name: 'Night Emergency Duty',
    shift_time: '08:00 PM – 08:00 AM',
    shift_status: 'NOT STARTED',
    is_night_shift: true,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(4),
  },
  {
    register_number: '24UEMT007',
    enrollment_number: '240015',
    name: 'SARAVANAN A',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_night_ahs',
    shift_name: 'Night Emergency Duty',
    shift_time: '08:00 PM – 08:00 AM',
    shift_status: 'NOT STARTED',
    is_night_shift: true,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(5),
  },
  {
    register_number: '24UEMT008',
    enrollment_number: '240095',
    name: 'VIKRAMAN M',
    department: 'Emergency Medicine Technology',
    posting_area: 'PRIORITY 1, PRIORITY 2, AMBULANCE SHIFTING, CASUALTY',
    mentor_id: 'mentor_emt_01',
    mentor_name: 'Dr. Dinesh Kumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_night_ahs',
    shift_name: 'Night Emergency Duty',
    shift_time: '08:00 PM – 08:00 AM',
    shift_status: 'NOT STARTED',
    is_night_shift: true,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(6),
  },

  // ==================== 5. B.Sc Medical Lab Technology (14) ====================
  {
    register_number: '23UMLT001',
    enrollment_number: '230105',
    name: 'AFRIN. J',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:35 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: '23UMLT002',
    enrollment_number: '230152',
    name: 'ANDI L',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:40 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: '23UMLT004',
    enrollment_number: '230076',
    name: 'DIVYA. E',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:48 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: '23UMLT005',
    enrollment_number: '230103',
    name: 'IYYANAR. A',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:52 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: '23UMLT006',
    enrollment_number: '230080',
    name: 'JESHIN. G. P',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:00 AM',
    avatar: getAvatar(3),
  },
  {
    register_number: '23UMLT007',
    enrollment_number: '230010',
    name: 'KOUSALYA. S',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:08 AM',
    avatar: getAvatar(4),
  },
  {
    register_number: '23UMLT009',
    enrollment_number: '230091',
    name: 'NAIRA SHARVI. J',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:12 AM',
    avatar: getAvatar(5),
  },
  {
    register_number: '24UMLT010',
    enrollment_number: '240153',
    name: 'NIRANJANA DEEP',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:15 AM',
    avatar: getAvatar(6),
  },
  {
    register_number: '23UMLT011',
    enrollment_number: '230011',
    name: 'PRABHA REGAN. H',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:55 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: '23UMLT012',
    enrollment_number: '230041',
    name: 'SHIVASHANKAR. T',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:42 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: '23UMLT013',
    enrollment_number: '230053',
    name: 'SUBASH. G',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(1),
  },
  {
    register_number: '23UMLT014',
    enrollment_number: '230038',
    name: 'YOGESHWARAN. S',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(2),
  },
  {
    register_number: '24UMLT015',
    enrollment_number: '240031',
    name: 'SATHISH KUMAR. S',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(3),
  },
  {
    register_number: '24UMLT002',
    enrollment_number: '240077',
    name: 'SRI GAYATHRI. M',
    department: 'Medical Lab Technology',
    posting_area: 'BIOCHEMISTRY LAB, PATHOLOGY LAB, MICRO LAB, BLOOD BANK, SEROLOGY, HEMATOLOGY',
    mentor_id: 'mentor_mlt_01',
    mentor_name: 'Dr. P. Sharmila',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(4),
  },

  // ==================== 6. B.Sc Operation Theatre & Anaesthesia Technology (10) ====================
  {
    register_number: '23UOTAT01',
    enrollment_number: '230087',
    name: 'ANUSUYA B',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:32 AM',
    avatar: getAvatar(5),
  },
  {
    register_number: '23UOTAT02',
    enrollment_number: '230005',
    name: 'BHAVANI R',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:40 AM',
    avatar: getAvatar(6),
  },
  {
    register_number: '23UOTAT04',
    enrollment_number: '230131',
    name: 'DHANUSH M',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:45 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: '23UOTAT05',
    enrollment_number: '230027',
    name: 'DHIVYA K',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:50 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: '23UOTAT06',
    enrollment_number: '230157',
    name: 'DINESH P',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:55 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: '23UOTAT07',
    enrollment_number: '230100',
    name: 'FATHIMA THANIHA SOODHA',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:02 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: '23UOTAT08',
    enrollment_number: '230101',
    name: 'HASEEN KALEELU RAHAMAN',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:10 AM',
    avatar: getAvatar(3),
  },
  {
    register_number: '23UOTAT09',
    enrollment_number: '230129',
    name: 'HIRA HANEERA',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(4),
  },
  {
    register_number: '23UOTAT10',
    enrollment_number: '230081',
    name: 'KANI DEVI K',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(5),
  },
  {
    register_number: '23UOTAT11',
    enrollment_number: '230090',
    name: 'SARASWATHI N',
    department: 'Operation Theatre & Anaesthesia Technology',
    posting_area: 'ORTHO OT, SPECIALTY OT, GENERAL OT, POST OPERATIVE CARE, PAC',
    mentor_id: 'mentor_otat_01',
    mentor_name: 'Dr. K. Rajesh',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_ot_ahs',
    shift_name: 'OT & Procedure Duty',
    shift_time: '08:30 AM – 04:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(6),
  },

  // ==================== 7. B.Sc Radiography and Imaging Technology (9) ====================
  {
    register_number: '23URIT001',
    enrollment_number: '230066',
    name: 'ANDREAS VIVEGANATHAN S',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:36 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: '24URIT002',
    enrollment_number: '240036',
    name: 'BHAVANI A',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:44 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: '24URIT004',
    enrollment_number: '240014',
    name: 'DIVAKAR M',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:52 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: '23URIT005',
    enrollment_number: '230040',
    name: 'MALLANI P',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:05 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: '23URIT006',
    enrollment_number: '230030',
    name: 'K. SANTHOKU',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:18 AM',
    avatar: getAvatar(3),
  },
  {
    register_number: '24URIT007',
    enrollment_number: '240012',
    name: 'SASITHA V',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_morning_ahs',
    shift_name: 'Morning Shift',
    shift_time: '08:00 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:25 AM',
    avatar: getAvatar(4),
  },
  {
    register_number: '23URIT008',
    enrollment_number: '230092',
    name: 'SHAFEEKA M',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(5),
  },
  {
    register_number: '23URIT009',
    enrollment_number: '230089',
    name: 'R. SIVARAJ',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(6),
  },
  {
    register_number: '23URIT010',
    enrollment_number: '230121',
    name: 'S. SURIYA',
    department: 'Radiography and Imaging Technology',
    posting_area: 'X-RAY, CT, MRI, USG, ANC',
    mentor_id: 'mentor_rit_01',
    mentor_name: 'Dr. V. Anand',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_evening_ahs',
    shift_name: 'Evening Shift',
    shift_time: '02:00 PM – 08:00 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(7),
  },

  // ==================== 8. B.Sc Neuro Care Technology (4) ====================
  {
    register_number: 'U23NCT002',
    enrollment_number: '230107',
    name: 'ADWAITHA J PRADEEP',
    department: 'Neuro Care Technology',
    posting_area: 'NEURO LAB',
    mentor_id: 'mentor_nct_01',
    mentor_name: 'Dr. T. Karthik',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:45 AM',
    avatar: getAvatar(0),
  },
  {
    register_number: 'U23NCT004',
    enrollment_number: '230089',
    name: 'JAYASRI',
    department: 'Neuro Care Technology',
    posting_area: 'NEURO LAB',
    mentor_id: 'mentor_nct_01',
    mentor_name: 'Dr. T. Karthik',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:50 AM',
    avatar: getAvatar(1),
  },
  {
    register_number: 'U23NCT005',
    enrollment_number: '230125',
    name: 'LOKESH',
    department: 'Neuro Care Technology',
    posting_area: 'NEURO LAB',
    mentor_id: 'mentor_nct_01',
    mentor_name: 'Dr. T. Karthik',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '09:05 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: 'U23NCT006',
    enrollment_number: '230162',
    name: 'MAHALAKSHMI',
    department: 'Neuro Care Technology',
    posting_area: 'NEURO LAB',
    mentor_id: 'mentor_nct_01',
    mentor_name: 'Dr. T. Karthik',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:58 AM',
    avatar: getAvatar(3),
  },

  // ==================== 9. B.Sc in Hematology & Blood Banking Technology (1) ====================
  {
    register_number: '24UHBBT01',
    enrollment_number: '240126',
    name: 'MONIKA R',
    department: 'Hematology & Blood Banking Technology',
    posting_area: 'BLOOD BANK',
    mentor_id: 'mentor_hbbt_01',
    mentor_name: 'Dr. S. Revathi',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:40 AM',
    avatar: getAvatar(4),
  },

  // ==================== 10. B.Sc in Renal Dialysis Technology (5) ====================
  {
    register_number: '23URDT001',
    enrollment_number: '230148',
    name: 'S CHANDRU',
    department: 'Renal Dialysis Technology',
    posting_area: 'DIALYSIS UNIT - 1',
    mentor_id: 'mentor_rdt_01',
    mentor_name: 'Dr. J. Sugumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_morn',
    shift_name: 'Dialysis Morning Shift',
    shift_time: '08:30 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:35 AM',
    avatar: getAvatar(5),
  },
  {
    register_number: '23URDT002',
    enrollment_number: '230154',
    name: 'S JAYASAKTHI',
    department: 'Renal Dialysis Technology',
    posting_area: 'DIALYSIS UNIT - 1',
    mentor_id: 'mentor_rdt_01',
    mentor_name: 'Dr. J. Sugumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_morn',
    shift_name: 'Dialysis Morning Shift',
    shift_time: '08:30 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:42 AM',
    avatar: getAvatar(6),
  },
  {
    register_number: '23URDT003',
    enrollment_number: '230075',
    name: 'J LAKSHMAN',
    department: 'Renal Dialysis Technology',
    posting_area: 'DIALYSIS UNIT - 1',
    mentor_id: 'mentor_rdt_01',
    mentor_name: 'Dr. J. Sugumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_morn',
    shift_name: 'Dialysis Morning Shift',
    shift_time: '08:30 AM – 02:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:48 AM',
    avatar: getAvatar(7),
  },
  {
    register_number: '23URDT004',
    enrollment_number: '230113',
    name: 'K NAVEENA',
    department: 'Renal Dialysis Technology',
    posting_area: 'DIALYSIS UNIT - 1',
    mentor_id: 'mentor_rdt_01',
    mentor_name: 'Dr. J. Sugumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_aft',
    shift_name: 'Dialysis Afternoon Shift',
    shift_time: '01:30 PM – 07:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(0),
  },
  {
    register_number: '23URDT005',
    enrollment_number: '230111',
    name: 'V SAVITHA SRI',
    department: 'Renal Dialysis Technology',
    posting_area: 'DIALYSIS UNIT - 1',
    mentor_id: 'mentor_rdt_01',
    mentor_name: 'Dr. J. Sugumar',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_dialysis_aft',
    shift_name: 'Dialysis Afternoon Shift',
    shift_time: '01:30 PM – 07:30 PM',
    shift_status: 'NOT STARTED',
    is_night_shift: false,
    is_active_shift: false,
    current_status: 'OFF SHIFT',
    avatar: getAvatar(1),
  },

  // ==================== 11. B.Sc Reproductive Medicine & Clinical Embryology (3) ====================
  {
    register_number: '24URME01',
    enrollment_number: '240112',
    name: 'I. NANDHAARASI',
    department: 'Reproductive Medicine & Clinical Embryology',
    posting_area: 'IVF OPD, ANDROLOGY LAB, LABOUR WARD',
    mentor_id: 'mentor_rmce_01',
    mentor_name: 'Dr. R. Gayathri',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:45 AM',
    avatar: getAvatar(2),
  },
  {
    register_number: '24URME02',
    enrollment_number: '240114',
    name: 'V. PRATHELA',
    department: 'Reproductive Medicine & Clinical Embryology',
    posting_area: 'IVF OPD, ANDROLOGY LAB, LABOUR WARD',
    mentor_id: 'mentor_rmce_01',
    mentor_name: 'Dr. R. Gayathri',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:50 AM',
    avatar: getAvatar(3),
  },
  {
    register_number: '24URME03',
    enrollment_number: '240092',
    name: 'VAYATHI DEEPIKA',
    department: 'Reproductive Medicine & Clinical Embryology',
    posting_area: 'IVF OPD, ANDROLOGY LAB, LABOUR WARD',
    mentor_id: 'mentor_rmce_01',
    mentor_name: 'Dr. R. Gayathri',
    hospital: 'Sri Manakula Vinayagar Medical College and Hospital (SMVMCH)',
    shift_id: 'shift_gen_ahs',
    shift_name: 'General Clinical Duty',
    shift_time: '08:30 AM – 04:00 PM',
    shift_status: 'ACTIVE',
    is_night_shift: false,
    is_active_shift: true,
    current_status: 'VERIFIED',
    last_verified_at: '08:58 AM',
    avatar: getAvatar(4),
  },
];

export const INITIAL_VERIFICATIONS: GpsVerification[] = [
  {
    id: 'v_abinaya_1',
    register_number: '23UCCT001',
    student_name: 'V. ABINAYA',
    department: 'Critical Care Technology',
    timestamp: '2026-09-05T08:30:00Z',
    time_display: '08:30 AM',
    status: 'VERIFIED',
    distance_meters: 35,
    accuracy_meters: 10,
    latitude: 11.9164,
    longitude: 79.6278,
    is_inside_geofence: true,
    verification_type: 'SHIFT_START',
  },
  {
    id: 'v_abinaya_2',
    register_number: '23UCCT001',
    student_name: 'V. ABINAYA',
    department: 'Critical Care Technology',
    timestamp: '2026-09-05T09:15:00Z',
    time_display: '09:15 AM',
    status: 'VERIFIED',
    distance_meters: 28,
    accuracy_meters: 8,
    latitude: 11.9163,
    longitude: 79.6277,
    is_inside_geofence: true,
    verification_type: 'SCHEDULED',
  },
  {
    id: 'v_anbarasan_1',
    register_number: '23UCCT002',
    student_name: 'M. ANBARASAN',
    department: 'Critical Care Technology',
    timestamp: '2026-09-05T08:45:00Z',
    time_display: '08:45 AM',
    status: 'VERIFIED',
    distance_meters: 42,
    accuracy_meters: 12,
    latitude: 11.9165,
    longitude: 79.6279,
    is_inside_geofence: true,
    verification_type: 'SHIFT_START',
  },
  {
    id: 'v_lourdhe_1',
    register_number: 'U23CLT009',
    student_name: 'I. LOURDHEMARY',
    department: 'Cardiac Lab Technology',
    timestamp: '2026-09-05T09:20:00Z',
    time_display: '09:20 AM',
    status: 'NEEDS ATTENTION',
    distance_meters: 380,
    accuracy_meters: 18,
    latitude: 11.9195,
    longitude: 79.6295,
    is_inside_geofence: false,
    verification_type: 'RANDOM_PROMPT',
    review_details: {
      reviewer_name: 'Dr. M. Suresh',
      reviewed_at: '2026-09-05 09:25',
      previous_status: 'NEEDS ATTENTION',
      review_notes: 'Temporary dispatch to diagnostic pharmacy wing',
    },
  },
];

export const INITIAL_ALERTS: DepartmentAlert[] = [
  {
    id: 'alert_lourdhe_01',
    verification_id: 'v_lourdhe_1',
    student_name: 'I. LOURDHEMARY',
    register_number: 'U23CLT009',
    department: 'Cardiac Lab Technology',
    mentor_id: 'mentor_clt_01',
    mentor_name: 'Dr. M. Suresh',
    shift_name: 'General Clinical Duty',
    triggered_at: '2026-09-05 09:20',
    time_display: '09:20 AM',
    status: 'NEEDS ATTENTION',
    distance_meters: 380,
    accuracy_meters: 18,
    reason: 'Geofence anomaly detected (380m from perimeter center in Cardiac Lab rotation). Contextual review required.',
  },
];

export const INITIAL_LOGS: AdminActivityLog[] = [
  {
    id: 'log_001',
    timestamp: '2026-09-05 08:30',
    actor: 'Admin User (admin01)',
    action: 'COHORT_INITIALIZED',
    action_type: 'STUDENT_ADD',
    target: 'SMVMCH School of Allied Health Sciences Interns (85 Students)',
    student_register_number: 'ALL-INTERNS',
    student_name: '85 AHS Interns Cohort',
    details: 'Loaded official clinical internship schedule across 11 allied health science departments',
    reason: 'New academic clinical internship cohort deployment',
    performed_by: 'SMVMCH Administration',
  },
  {
    id: 'log_002',
    timestamp: '2026-09-05 08:32',
    actor: 'System Automation',
    action: 'SHIFT_START_VERIFIED',
    action_type: 'STUDENT_EDIT',
    target: 'V. ABINAYA (23UCCT001)',
    student_register_number: '23UCCT001',
    student_name: 'V. ABINAYA',
    details: 'Shift check-in confirmed via clinical geofence validation (35m distance)',
    reason: 'Regular clinical shift start',
    performed_by: 'System Telemetry',
  },
];

export const INITIAL_ATTENDANCE_RECORDS: StudentAttendanceRecord[] = [
  {
    id: 'att_05sep',
    register_number: '23UCCT001',
    date_display: '05 Sep 2026',
    date_iso: '2026-09-05',
    shift_name: 'General Day',
    time_window: '08:30 AM – 04:00 PM',
    start_time: '08:30 AM',
    end_time: 'In Progress',
    status: 'IN PROGRESS',
    verified_checks: 2,
    total_checks: 2,
    hours_logged: '1.0 hrs',
    mentor_name: 'Dr. S. Priya',
    period_group: 'THIS_WEEK',
  },
  {
    id: 'att_04sep',
    register_number: '23UCCT001',
    date_display: '04 Sep 2026',
    date_iso: '2026-09-04',
    shift_name: 'General Day',
    time_window: '08:30 AM – 04:00 PM',
    start_time: '08:30 AM',
    end_time: '04:00 PM',
    status: 'COMPLETED',
    verified_checks: 4,
    total_checks: 4,
    hours_logged: '7.5 hrs',
    mentor_name: 'Dr. S. Priya',
    period_group: 'THIS_WEEK',
  },
];

export const INITIAL_STUDENT_NOTIFICATIONS: StudentNotification[] = [
  {
    id: 'notif_01',
    register_number: '23UCCT001',
    type: 'SHIFT_REMINDER',
    title: 'Clinical Shift Active',
    message: 'Your General Clinical Duty in Critical Care Technology (ICU, General Medicine Ward) is underway.',
    timestamp: '2026-09-05T08:30:00Z',
    time_display: '08:30 AM',
    is_read: false,
    priority: 'HIGH',
  },
  {
    id: 'notif_02',
    register_number: '23UCCT001',
    type: 'VERIFICATION_RESULT',
    title: 'Presence Verified in Hospital',
    message: 'Your presence at SMVMCH ICU Block was successfully verified (35m from center, ±10m accuracy).',
    timestamp: '2026-09-05T08:31:00Z',
    time_display: '08:31 AM',
    is_read: true,
    priority: 'NORMAL',
  },
];

export const INITIAL_MENTOR_NOTIFICATIONS: MentorNotification[] = [
  {
    id: 'mnotif_01',
    mentor_id: 'mentor_clt_01',
    type: 'NEEDS_ATTENTION_ALERT',
    title: 'Geofence Anomaly - I. LOURDHEMARY',
    message: 'Intern I. LOURDHEMARY (U23CLT009) recorded a 380m distance check during clinical duty. Please review.',
    timestamp: '2026-09-05T09:20:00Z',
    time_display: '09:20 AM',
    is_read: false,
    priority: 'HIGH',
    student_register_number: 'U23CLT009',
    student_name: 'I. LOURDHEMARY',
    alert_id: 'alert_lourdhe_01',
  },
];

export const DEMO_USERS: Record<string, UserProfile> = {
  '23UCCT001': {
    id: '23UCCT001',
    registerNumber: '23UCCT001',
    name: 'V. ABINAYA',
    role: 'STUDENT',
    department: 'Critical Care Technology',
    email: '23ucct001@smvmch.edu.in',
    avatar: getAvatar(0),
    password: 'Student@2026',
  },
  mentor01: {
    id: 'mentor_cct_01',
    name: 'Dr. S. Priya',
    role: 'MENTOR',
    department: 'Critical Care Technology',
    email: 'dr.priya@smvmch.edu.in',
    avatar: 'https://images.unsplash.com/photo-1594824813589-3221e7d23d8c?w=150&auto=format&fit=crop&q=80',
    password: 'Mentor@2026',
  },
  hod01: {
    id: 'hod_cct',
    name: 'Dr. K. Senthil Nathan',
    role: 'HOD',
    department: 'Critical Care Technology',
    email: 'hod.cct@smvmch.edu.in',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    password: 'Hod@2026',
  },
  admin01: {
    id: 'admin01',
    name: 'SMVMCH AHS Academic Cell',
    role: 'ADMIN',
    department: 'School of Allied Health Sciences',
    email: 'admin.ahs@smvmch.edu.in',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    password: 'Admin@2026',
  },
};
